window:
  theme: Darcula
  height: 700
  width: 1200

editor:
  fontSize: 16
  fontFamily: Monospaced
  theme: monokai
  tabSize: 4
  wordWrap: false
  lineNumbers: true
  codeFolding: true
  markOccurrences: true
  marginLinePosition: 100

sidebar:
  visible: false
  width: 250

lastOpenedFolder: ""
recentFiles: []
